+const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
+const ui = {score:document.querySelector('#score'),coins:document.querySelector('#coins'),best:document.querySelector('#best'),start:document.querySelector('#startScreen'),over:document.querySelector('#gameOver'),startBtn:document.querySelector('#startBtn'),restart:document.querySelector('#restartBtn'),result:document.querySelector('#result'),resultBest:document.querySelector('#resultBest'),toast:document.querySelector('#toast'),sound:document.querySelector('#sound')};
+let W,H,ground, state='intro', last=0, score=0, barsiki=0, best=+localStorage.getItem('barsik-best')||0, speed=350, elapsed=0, spawn=0, coinSpawn=0, objects=[], particles=[], shield=false, soundOn=true, slide=false, touchY=0, milestones=new Set();
+const barsikSprite = new Image();
+barsikSprite.src = 'barsik-source.gif';
+const player={x:0,y:0,w:82,h:112,vy:0,onGround:true,run:0};
+function resize(){ const d=Math.min(devicePixelRatio||1,2); W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);ground=H*.77;player.x=Math.max(65,W*.16); if(player.onGround)player.y=ground-player.h }
+addEventListener('resize',resize);resize();
+function fmt(n,l=5){return String(Math.floor(n)).padStart(l,'0')}function updateUI(){ui.score.textContent=fmt(score);ui.coins.textContent=fmt(barsiki,3);ui.best.textContent=fmt(best)}updateUI();
+function tone(freq,d=.08,type='sine'){if(!soundOn)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(e){}}
+function toast(text){ui.toast.textContent=text;ui.toast.classList.add('show');setTimeout(()=>ui.toast.classList.remove('show'),1600)}
+function reset(){score=0;barsiki=0;speed=350;elapsed=spawn=coinSpawn=0;objects=[];particles=[];shield=false;slide=false;milestones.clear();player.h=112;player.vy=0;player.onGround=true;player.y=ground-player.h;updateUI()}
+function start(){reset();state='running';ui.start.classList.remove('active');ui.over.classList.remove('active');toast('ВРЕМЯ БЕЖАТЬ!');last=performance.now();requestAnimationFrame(loop)}
+ui.startBtn.onclick=start;ui.restart.onclick=start;ui.sound.onclick=()=>{soundOn=!soundOn;ui.sound.textContent=soundOn?'♪':'×';ui.sound.setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')};
+function jump(){if(state==='intro')return start();if(state!=='running'||!player.onGround)return;player.vy=-650;player.onGround=false;tone(420,.1,'square')}
+function setSlide(on){if(state!=='running'||!player.onGround)return;slide=on;player.h=on?68:112;player.y=ground-player.h}
+addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Space'||e.code==='ArrowUp')jump();if(e.code==='ArrowDown')setSlide(true)});addEventListener('keyup',e=>{if(e.code==='ArrowDown')setSlide(false)});
+canvas.addEventListener('pointerdown',e=>{touchY=e.clientY;if(e.pointerType==='mouse')jump()});canvas.addEventListener('pointerup',e=>{if(e.pointerType!=='mouse'){if(e.clientY-touchY>40)setSlide(false);else jump()}setSlide(false)});canvas.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'&&e.clientY-touchY>40)setSlide(true)});
+function addObject(){let kinds=elapsed<12?['puddle','bin','barrier']:['puddle','bin','barrier','scooter','bench','person','bike'];let kind=kinds[Math.floor(Math.random()*kinds.length)], tall=['person','bike'].includes(kind), w={puddle:60,bin:34,barrier:62,scooter:42,bench:75,person:36,bike:60}[kind], h=tall?68:{puddle:10,bin:42,barrier:35,scooter:43,bench:39}[kind];objects.push({kind,x:W+w,y:ground-h,w,h,hit:false});if(Math.random()<Math.min(.24,elapsed/140))setTimeout(()=>objects.push({kind:'barrier',x:W+w+150,y:ground-35,w:62,h:35,hit:false}),600)}
+function addCoin(){let rare=Math.random()<.13;objects.push({kind:rare?'gold':'coin',x:W+30,y:ground-(70+Math.random()*90),w:30,h:30,value:rare?5:1,hit:false})}
+function addBonus(){objects.push({kind:'dms',x:W+38,y:ground-115,w:42,h:42,hit:false})}
+function hit(a,b){return a.x+12<b.x+b.w-8&&a.x+a.w-12>b.x+8&&a.y+9<b.y+b.h-5&&a.y+a.h-5>b.y+5}
+function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*190,vy:(Math.random()-.7)*190,t:0.55,color})}
+function end(){state='over';tone(110,.35,'sawtooth');best=Math.max(best,score);localStorage.setItem('barsik-best',best);updateUI();ui.result.textContent=`SCORE: ${fmt(score)} · БАРСИКИ: ${fmt(barsiki,3)}`;ui.resultBest.textContent=fmt(best);setTimeout(()=>ui.over.classList.add('active'),500)}
+function update(dt){elapsed+=dt;speed=Math.min(720,350+elapsed*7);score+=dt*10*(1+Math.floor(elapsed/24)*.15);spawn-=dt;coinSpawn-=dt;if(spawn<=0){addObject();spawn=Math.max(.72,1.65-elapsed*.018)+Math.random()*.45}if(coinSpawn<=0){addCoin();if(Math.random()<.035)addBonus();coinSpawn=1.4+Math.random()*2.1+elapsed*.012}player.run+=dt*15;player.vy+=1750*dt;player.y+=player.vy*dt;if(player.y>=ground-player.h){player.y=ground-player.h;player.vy=0;player.onGround=true}const box={x:player.x,y:player.y,w:player.w,h:player.h};objects.forEach(o=>{o.x-=speed*dt;if(!o.hit&&hit(box,o)){o.hit=true;if(o.kind==='coin'||o.kind==='gold'){barsiki+=o.value;score+=o.value*30;burst(o.x,o.y,o.kind==='gold'?'#ffd234':'#b9f05c');tone(o.kind==='gold'?820:680,.09);toast(o.kind==='gold'?'+5 ЗОЛОТОЙ БАРСИК!':'+1 БАРСИК')}else if(o.kind==='dms'){shield=true;burst(o.x,o.y,'#56c8f3');tone(880,.18);toast('ДМС СПАСАЕТ!')}else if(shield){shield=false;burst(player.x+35,player.y+45,'#7de5ff',18);toast('ДМС СПАСАЕТ!');tone(300,.12)}else end()}});objects=objects.filter(o=>o.x+o.w>-80&&!o.hit);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=440*dt;p.t-=dt});particles=particles.filter(p=>p.t>0);[120,300,600,1000].forEach((m,i)=>{if(score>=m&&!milestones.has(m)){milestones.add(m);toast(['УСПЕВАЕТ!','ЕЩЁ НЕМНОГО!','БАРСИК УЖЕ БЛИЗКО!','ОФИС УЖЕ ВИДЕН!'][i]); if(m===1000)tone(960,.25)}});if(score>2200&&!milestones.has(2200)){milestones.add(2200);toast('БАРСИК УСПЕЛ! НОВЫЙ КРУГ!');speed+=70}updateUI()}
+function rect(x,y,w,h,c,r=0){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}function draw(){ctx.clearRect(0,0,W,H);let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#85dff2');sky.addColorStop(.6,'#dff8f3');sky.addColorStop(1,'#effde4');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H); // clouds
+ctx.fillStyle='#fff9';for(let i=0;i<5;i++){let x=((i*270-elapsed*8)%(W+300))-80,y=65+(i%3)*46;ctx.beginPath();ctx.arc(x,y,22,0,7);ctx.arc(x+25,y-12,30,0,7);ctx.arc(x+58,y,20,0,7);ctx.fill()}
+// skyline
+let off=(elapsed*15)%(120);for(let x=-120-off;x<W+120;x+=120){let h=80+((x/120|0)%3)*30;rect(x,ground-h-35,78,h,'#92c7c5',5);for(let yy=ground-h-20;yy<ground-48;yy+=18)for(let xx=x+12;xx<x+65;xx+=18)rect(xx,yy,7,8,'#dff8b2',2)}
+// bank building far
+let bx=W*.73-(elapsed*7%(W+300));if(bx>-190&&bx<W+100){rect(bx,ground-182,140,150,'#087f58',8);rect(bx+13,ground-166,114,18,'#ddf574',3);ctx.fillStyle='white';ctx.font='900 11px Montserrat';ctx.fillText('АК БАРС БАНК',bx+22,ground-152);for(let yy=ground-125;yy<ground-45;yy+=24)for(let xx=bx+18;xx<bx+120;xx+=24)rect(xx,yy,12,12,'#a3e2e6',2)}
+// trees
+let toff=(elapsed*45)%150;for(let x=-150-toff;x<W+150;x+=150){rect(x+45,ground-91,8,60,'#806344');ctx.fillStyle='#4aaf68';ctx.beginPath();ctx.arc(x+49,ground-104,32,0,7);ctx.arc(x+24,ground-82,24,0,7);ctx.arc(x+73,ground-79,25,0,7);ctx.fill()}
+rect(0,ground-31,W,31,'#8bc86c');rect(0,ground,W,H-ground,'#55636a');rect(0,ground+9,W,5,'#eff1d5');ctx.fillStyle='#f9f4c8';for(let x=-(elapsed*speed*.55%100);x<W;x+=100)ctx.fillRect(x,ground+74,55,6);
+objects.forEach(drawObject);drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.t*2);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,4,0,7);ctx.fill();ctx.globalAlpha=1})}
+function drawObject(o){let x=o.x,y=o.y;ctx.save();if(o.kind==='coin'||o.kind==='gold'){ctx.fillStyle=o.kind==='gold'?'#ffc933':'#b6ef50';ctx.beginPath();ctx.arc(x+15,y+15,15,0,7);ctx.fill();ctx.strokeStyle='#087f58';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#087f58';ctx.font='900 17px Arial';ctx.fillText('₿',x+10,y+21)}else if(o.kind==='dms'){ctx.fillStyle='#e8fbff';ctx.strokeStyle='#159bd1';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x+21,y+21,19,0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#1687bc';ctx.font='900 10px Montserrat';ctx.fillText('ДМС',x+8,y+24)}else if(o.kind==='puddle'){ctx.fillStyle='#3694bf';ctx.beginPath();ctx.ellipse(x+30,y+7,30,8,0,0,7);ctx.fill()}else if(o.kind==='bin'){rect(x+4,y+8,26,34,'#347e77',4);rect(x,y+3,34,8,'#235c5b',3)}else if(o.kind==='barrier'){rect(x,y+12,o.w,15,'#f3a33a',3);rect(x+8,y,o.w-16,10,'#fff1bc',2);for(let i=5;i<o.w;i+=20)rect(x+i,y+12,9,15,'#fff4d2')}else if(o.kind==='scooter'){ctx.strokeStyle='#273d42';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x+12,y+39);ctx.lineTo(x+31,y+5);ctx.lineTo(x+35,y+39);ctx.lineTo(x+6,y+39);ctx.stroke();ctx.fillStyle='#16ae78';ctx.beginPath();ctx.arc(x+9,y+40,5,0,7);ctx.arc(x+35,y+40,5,0,7);ctx.fill()}else if(o.kind==='bench'){rect(x,y+15,o.w,10,'#b97845',2);rect(x+8,y+27,7,12,'#654530');rect(x+o.w-15,y+27,7,12,'#654530');rect(x+3,y+2,o.w-6,9,'#d28a4e',2)}else if(o.kind==='person'){ctx.fillStyle='#244b77';ctx.beginPath();ctx.arc(x+18,y+10,11,0,7);ctx.fill();rect(x+7,y+22,22,35,'#e47d56',9);ctx.strokeStyle='#243b45';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x+12,y+55);ctx.lineTo(x+7,y+68);ctx.moveTo(x+25,y+55);ctx.lineTo(x+30,y+68);ctx.stroke()}else {ctx.strokeStyle='#34454a';ctx.lineWidth=4;ctx.beginPath();ctx.arc(x+13,y+50,10,0,7);ctx.arc(x+47,y+50,10,0,7);ctx.moveTo(x+13,y+50);ctx.lineTo(x+28,y+24);ctx.lineTo(x+47,y+50);ctx.lineTo(x+21,y+50);ctx.lineTo(x+40,y+18);ctx.stroke();ctx.fillStyle='#ee7654';ctx.beginPath();ctx.arc(x+35,y+10,10,0,7);ctx.fill()}ctx.restore()}
+function drawPlayer(){
+  const x=player.x, y=player.y, h=player.h;
+  const stride=Math.sin(player.run), bounce=player.onGround ? Math.abs(stride)*4 : 0;
+  ctx.save();
+  if(shield){ctx.strokeStyle='#52d4f3aa';ctx.lineWidth=5;ctx.beginPath();ctx.arc(x+42,y+h/2,63,0,7);ctx.stroke()}
+  // Длинный хвост и беговые тени создают читаемый профиль и движение справа налево.
+  ctx.strokeStyle='#f1f0df';ctx.lineWidth=18;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x+24,y+h-31);ctx.quadraticCurveTo(x-26,y+h-4,x-11,y+h-57);ctx.stroke();
+  ctx.strokeStyle='#40483e';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x-17,y+h-40);ctx.lineTo(x-8,y+h-28);ctx.stroke();
+  ctx.fillStyle='#31474b33';ctx.beginPath();ctx.ellipse(x+44,ground+3,45+Math.abs(stride)*5,6,0,0,7);ctx.fill();
+  // Оригинальное фото Барсика — сжатие по X и наклон задают бегущий 3/4-профиль вправо.
+  if(barsikSprite.complete && barsikSprite.naturalWidth){
+    ctx.translate(x+42,y+h-5-bounce);ctx.rotate(-.055+stride*.025);ctx.scale(.72,1);
+    ctx.drawImage(barsikSprite,-64,-132,128,132);
+  }else{rect(x+12,y+16,55,74,'#f8f6e9',24)}
+  // Ритмичные линии у ног усиливают анимацию бега, не закрывая фотографию.
+  ctx.strokeStyle='#0f7c59';ctx.lineWidth=3;ctx.globalAlpha=.55;ctx.beginPath();ctx.moveTo(x+5,y+h-15);ctx.lineTo(x-8,y+h-12);ctx.moveTo(x+9,y+h-7);ctx.lineTo(x-5,y+h-5);ctx.stroke();ctx.globalAlpha=1;
+  ctx.restore()
+}
+function loop(t){let dt=Math.min(.034,(t-last)/1000);last=t;if(state==='running')update(dt);draw();if(state==='running')requestAnimationFrame(loop)}draw();
